# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_meshed_geometry.ipynb (unless otherwise specified).

__all__ = ['get_circle_info', 'add_domain_physical_tags', 'add_boundary_physical_tags', 'add_disks_rectangle',
           'identify_rectangle_disk_tags', 'make_msh']

# Cell
import os

# Cell
import numpy as np
import gmsh

from . import AbstractGeometry

# Cell
def get_circle_info(circle):
    x, y = list(circle.centroid.coords)[0]
    r = circle.length / (np.pi * 2)
    return x, y, r

# Cell
def add_domain_physical_tags(rectangle_tags, disk_tags, model):
    model.addPhysicalGroup(2, tags=rectangle_tags, tag=2)
    model.setPhysicalName(2, tag=2, name="weak material")

    model.addPhysicalGroup(2, tags=disk_tags, tag=1)
    model.setPhysicalName(2, tag=1, name="strong material")

# Cell
def add_boundary_physical_tags(box_coord_dim, model):
    x_b, y_b, dx_b, dy_b = box_coord_dim

    eps=1e-3
    limits_right = x_b+dx_b-eps, y_b-eps, -eps, x_b+dx_b+eps, y_b+dy_b+eps, +eps
    limits_left = x_b-eps, y_b-eps, -eps, x_b+eps, y_b+dy_b+eps, +eps
    limits_top = x_b-eps, y_b+dy_b-eps, -eps, x_b+dx_b+eps, y_b+dy_b+eps, +eps
    limits_bot = x_b-eps, y_b-eps, -eps, x_b+dx_b+eps, y_b+eps, +eps

    def add(limits, tag, name):
        vs = model.getEntitiesInBoundingBox(
            *limits,
            dim=1
        )

        model.addPhysicalGroup(1, tags=[v[1] for v in vs], tag=tag)
        model.setPhysicalName(1, tag=tag, name=name)

    add(limits_right, 5, 'right')
    add(limits_left, 3, 'left')
    add(limits_top, 6, 'top')
    add(limits_bot, 4, 'bot')

# Cell
def add_disks_rectangle(box_coord_dim, circles, factory, model):
    x_b, y_b, dx_b, dy_b = box_coord_dim
    rectangle = (2, factory.addRectangle(x_b, y_b, 0, dx_b, dy_b))

    disks = []
    for circle in circles:
        x, y, r = get_circle_info(circle)
        disk = factory.addDisk(x, y, 0, r, r)
        disks.append((2, disk))

    ov, ovv = factory.fragment([rectangle], disks)

    # # Without synchronization the entities in the OpenCASCADE CAD
    # # representation are not available to any function outside of
    # # the OpenCASCADE CAD kernel functions
    factory.synchronize()

    eps=1e-3
    vin = model.getEntitiesInBoundingBox(
        x_b-eps, y_b-eps, -eps, x_b+dx_b+eps, y_b+dy_b+eps, +eps,
        dim=2
    )

    # print('entities in')
    # print(vin)

    # print('fragment produced surfaces')
    # print([o[1] for o in ov])
    # print()

    # print('before/after frament rel')
    # for e in zip([rectangle] + disks, ovv):
    #     print(e[0], '->', e[1])

    # for v in vin:
    #     ov.remove(v)
    # model.removeEntities(ov, True)

    rectangle_tags, disk_tags = identify_rectangle_disk_tags(ov, ovv)

    return rectangle_tags, disk_tags

# Cell
def identify_rectangle_disk_tags(ov, ovv):
    ovv_disks = ovv[1:]
    ovv_rect = ovv[0]

    inner_disks = []
    for ov in ovv_disks:
        for o in ov:
            if o in ovv_rect:
                inner_disks.append(o)

    rectangle = [o for o in ovv_rect if o not in inner_disks]

    disk_tags = [t for _, t in inner_disks]
    rectangle_tags = [t for _, t in rectangle]

    return rectangle_tags, disk_tags

# Cell
def make_msh(output_path, abstract_geometry):
    circles, box_coord_dim = abstract_geometry.get_geom_info()

    model = gmsh.model
    factory = model.occ

    # gmsh.clear()
    gmsh.initialize()
    gmsh.option.setNumber("General.Verbosity", 0)
    gmsh.option.setNumber("Mesh.MshFileVersion", 2.2)
    gmsh.option.setNumber("Mesh.RecombinationAlgorithm", 2)
    gmsh.option.setNumber("Mesh.RecombineAll", 2)

    rectangle_tags, disk_tags = add_disks_rectangle(box_coord_dim, circles, factory, model)

    add_domain_physical_tags(rectangle_tags, disk_tags, model)

    add_boundary_physical_tags(box_coord_dim, model)

    factory.synchronize()

    _, _, dx, dy = box_coord_dim
    gmsh.option.setNumber("Mesh.MeshSizeMin", (dx+dy)/100)
    gmsh.option.setNumber("Mesh.MeshSizeMax", (dx+dy)/100)
    model.mesh.generate(dim=2)
    # gmsh.model.mesh.refine()
    gmsh.write(output_path)

    gmsh.finalize()