# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_rasterized_geometry.ipynb (unless otherwise specified).

__all__ = ['GeometryRasterizer']

# Cell
from shapely.geometry import Point, box, Polygon, MultiPoint, MultiPolygon, LineString, MultiLineString
from geocube.api.core import make_geocube
import geopandas as gpd
import numpy as np


from . import AbstractGeometry

# Cell
class GeometryRasterizer:
    def __init__(self, abstract_geometry: AbstractGeometry):
        self.circle_centers, self.circle_radius, self.box_corner_coords = abstract_geometry.get_geom_info()
        self.box_size = abstract_geometry.box_size
        self.elements = {}
        self.geocube = None

    def get_label_fields(self):
        if self.geocube:
            return self.geocube.labels.x.data, self.geocube.labels.y.data, self.geocube.labels.data

    def rasterize(self, resolution=(1, 1)):
        circles = self._make_circles()
        boxx = self._make_box(circles)
        boundary_bot, boundary_right, boundary_top, boundary_left = self._make_boundaries()

        self._add_element('holes', 1, circles)
        self._add_element('box_wo_holes', 2, boxx)
        self._add_element('boundary_left', 3, boundary_left)
        self._add_element('boundary_bot', 4, boundary_bot)
        self._add_element('boundary_right', 5, boundary_right)
        self._add_element('boundary_top', 6, boundary_top)
        self._add_element('circle_boundary', 7, circles.boundary)

        g = gpd.GeoDataFrame(
            {"labels": [element[0] for element in self.elements.values()]},
            geometry=[element[1] for element in self.elements.values()],
            crs={"init": "epsg:4326"}
        )

        self.geocube = make_geocube(vector_data=g, resolution=resolution, fill=0)

    def _add_element(self, name, label, element):
        self.elements.update({name: [label, element]})

    def _make_circles(self):
        return MultiPoint(self.circle_centers).buffer(self.circle_radius)

    def _make_box(self, circles):
        boxx = box(0, 0, self.box_size[0], self.box_size[1])
        return boxx.difference(circles)

    def _adjust_box_coordinates(self):
        self.box_corner_coords[1][0] *= 0.999
        self.box_corner_coords[2][0] *= 0.999
        self.box_corner_coords[2][1] *= 0.999
        self.box_corner_coords[3][1] *= 0.999

    def _make_boundaries(self):
        self._adjust_box_coordinates()

        boundary_bot = LineString([self.box_corner_coords[0], self.box_corner_coords[1]])
        boundary_right = LineString([self.box_corner_coords[1], self.box_corner_coords[2]])
        boundary_top = LineString([self.box_corner_coords[2], self.box_corner_coords[3]])
        boundary_left = LineString([self.box_corner_coords[3], self.box_corner_coords[0]])

        return boundary_bot, boundary_right, boundary_top, boundary_left