# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_rasterized_geometry.ipynb (unless otherwise specified).

__all__ = ['element_to_tag', 'GeometryRasterizer']

# Cell
from shapely.geometry import Point, box, Polygon, MultiPoint, MultiPolygon, LineString, MultiLineString
from geocube.api.core import make_geocube
import geopandas as gpd
import numpy as np

from . import AbstractGeometry

# Cell
element_to_tag = {
    "circles": 1,
    "box_wo_circles": 2,
    "circles_boundaries": 3
}

# Cell
class GeometryRasterizer:
    def __init__(self, resolution):
        self.resolution = resolution

    def __call__(self, abstract_geometry: AbstractGeometry):
        circles, box_coord_dim = abstract_geometry.get_geom_info()

        grid_size = self._calculate_grid_size(box_coord_dim)

        boxx = self._make_box(circles, box_coord_dim)

        vector_data = self._make_geopandas_dataframe(circles, boxx)

        raster_array = make_geocube(
            vector_data=vector_data,
            resolution=grid_size,
            fill=0)

        x = np.array(raster_array.x)
        y = np.array(raster_array.y)
        raster_image = np.array(raster_array.tags)

        return x, y, raster_image

    def _calculate_grid_size(self, box_coord_dim):
        x, y, dx, dy = box_coord_dim
        grid_size = (dx/self.resolution[0], dy/self.resolution[1])
        return grid_size

    def _make_geopandas_dataframe(self, circles, boxx):
        tags = list(element_to_tag.values())
        geometries = [circles, boxx, circles.boundary]

        g = gpd.GeoDataFrame(
            {"tags": tags},
            geometry=geometries
        )
        return g

    def _make_box(self, circles, box_coord_dim):
        x, y, dx, dy = box_coord_dim
        boxx = box(x, y, x+dx, y+dy)
        return boxx.difference(circles)