# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/notebooks/01_rasterized_geometry.ipynb (unless otherwise specified).

__all__ = ['element_to_tag', 'GeometryRasterizer']

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Cell
from shapely.geometry import Point, box, Polygon, MultiPoint, MultiPolygon, LineString, MultiLineString
from geocube.api.core import make_geocube
import geopandas as gpd
import numpy as np

from . import AbstractGeometry

# Cell
element_to_tag = {
    "circles": 1,
    "box_wo_circles": 2,
    "circles_boundaries": 3
}

# Cell
class GeometryRasterizer:
    def __init__(self, resolution):
        self.resolution = resolution

    def __call__(self, abstract_geometry: AbstractGeometry):
        circles, _ = abstract_geometry.get_geom_info()
        
        x_max, y_max = abstract_geometry.box_size
        grid_size = (x_max/self.resolution[0], y_max/self.resolution[1])

        boxx = self._make_box(circles, box_size=abstract_geometry.box_size)
        
        vector_data = self._make_geopandas_dataframe(circles, boxx)
        
        raster_array = make_geocube(
            vector_data=vector_data,
            resolution=grid_size,
            fill=0)

        return raster_array

    def _make_geopandas_dataframe(self, circles, boxx):
        tags = list(element_to_tag.values())
        geometries = [circles, boxx, circles.boundary]
        
        g = gpd.GeoDataFrame(
            {"tags": tags},
            geometry=geometries,
            crs={"init": "EPSG:4326"}
        )
        
        return g

    def _make_box(self, circles, box_size):
        boxx = box(0, 0, box_size[0], box_size[1])
        return boxx.difference(circles)