# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AbstractGeometry": "00_abstract_geometry.ipynb",
         "make_msh": "01_meshed_geometry.ipynb"}

modules = ["geometry/abstract_geometry.py",
           "geometry/meshed_geometry.py",
           "geometry/rasterized_geometry.py"]

doc_url = "https://fghavamian.github.io/accelerate_simulations/"

git_url = "https://github.com/fghavamian/accelerate_simulations/tree/master/"

def custom_doc_links(name): return None
