# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AbstractGeometry": "00_abstract_geometry.ipynb",
         "make_msh": "01_meshed_geometry.ipynb",
         "VTUContent": "02_preprocess.ipynb",
         "read_vtu_files": "02_preprocess.ipynb",
         "make_grid": "02_preprocess.ipynb",
         "compute_tri3_shape_function_at": "02_preprocess.ipynb",
         "find_grids_in_each_element": "02_preprocess.ipynb",
         "interpolate": "02_preprocess.ipynb",
         "GeometryRasterizer": "01_rasterized_geometry.ipynb",
         "MaterialFieldMaker": "02_input_fields.ipynb",
         "GeometricFieldMaker": "02_input_fields.ipynb"}

modules = ["geometry/abstract_geometry.py",
           "geometry/meshed_geometry.py",
           "geometry/rasterized_geometry.py",
           "preprocess/interpolate_target.py",
           "preprocess/input_fields.py"]

doc_url = "https://fghavamian.github.io/accelerate_simulations/"

git_url = "https://github.com/fghavamian/accelerate_simulations/tree/master/"

def custom_doc_links(name): return None
