# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/03_train.ipynb (unless otherwise specified).

__all__ = ['load_data', 'GoogleNetLayer', 'GoogleNetTransposedLayer', 'UnetModel', 'get_compiled_UnetModel',
           'plot_example']

# Cell
import os

import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

# Cell
def load_data(path_processed_data):
    path_inputs = os.path.join(path_processed_data, 'input.npy')
    path_targets = os.path.join(path_processed_data, 'target.npy')

    inputs = np.load(path_inputs)
    targets = np.load(path_targets)

    inputs = inputs[:, :, :, :5]   # only considering geometric fields
    targets = targets*1e4   # sclaing plastic strain to more regular range

    inputs = inputs.astype('float32')
    targets = targets.astype('float32')

    return inputs, targets

# Cell
class GoogleNetLayer(tf.keras.layers.Layer):
    def __init__(self, n_filters, kernel_sizes, strides, name, dtype='float32', autocast=False, **kwargs):
        super(GoogleNetLayer, self).__init__(name=name, dtype=dtype, **kwargs)

        default_params = dict(filters=n_filters, strides=strides, padding='same', activation='relu')

        self.conv1 = tf.keras.layers.Conv2D(kernel_size=kernel_sizes[0], **default_params)
        self.conv2 = tf.keras.layers.Conv2D(kernel_size=kernel_sizes[1], **default_params)
        self.conv3 = tf.keras.layers.Conv2D(kernel_size=kernel_sizes[2], **default_params)
        self.concat = tf.keras.layers.Concatenate()

    def call(self, inputs):
        c1 = self.conv1(inputs)
        c2 = self.conv1(inputs)
        c3 = self.conv1(inputs)
        return self.concat([c1, c2, c3])

# Cell
class GoogleNetTransposedLayer(tf.keras.layers.Layer):
    def __init__(self, n_filters, kernel_sizes, strides, name, dtype='float32', **kwargs):
        super(GoogleNetTransposedLayer, self).__init__(name=name, dtype=dtype, **kwargs)

        default_params = dict(filters=n_filters, strides=strides, padding='same', activation='relu')

        self.convt1 = tf.keras.layers.Conv2DTranspose(kernel_size=kernel_sizes[0], **default_params)
        self.convt2 = tf.keras.layers.Conv2DTranspose(kernel_size=kernel_sizes[1], **default_params)
        self.convt3 = tf.keras.layers.Conv2DTranspose(kernel_size=kernel_sizes[2], **default_params)
        self.concat = tf.keras.layers.Concatenate()

    def call(self, inputs):
        c1 = self.convt1(inputs)
        c2 = self.convt1(inputs)
        c3 = self.convt1(inputs)
        return self.concat([c1, c2, c3])

# Cell
class UnetModel(tf.keras.Model):
    def __init__(self, kernel_sizes, filter_sizes):
        super(UnetModel, self).__init__()
        self.d1_layer = GoogleNetLayer(filter_sizes[0], kernel_sizes, strides=(1,1), name='d1')
        self.d2_layer = GoogleNetLayer(filter_sizes[1], kernel_sizes, strides=(2,2), name='d2')
        self.d3_layer = GoogleNetLayer(filter_sizes[2], kernel_sizes, strides=(1,1), name='d3')
        self.d4_layer = GoogleNetLayer(filter_sizes[3], kernel_sizes, strides=(2,2), name='d4')

        self.u4_layer = GoogleNetTransposedLayer(filter_sizes[3], kernel_sizes, strides=(1,1), name='u4')
        self.u3_layer = GoogleNetTransposedLayer(filter_sizes[2], kernel_sizes, strides=(2,2), name='u3')
        self.u2_layer = GoogleNetTransposedLayer(filter_sizes[1], kernel_sizes, strides=(1,1), name='u2')
        self.u1_layer = GoogleNetTransposedLayer(filter_sizes[0], kernel_sizes, strides=(2,2), name='u1')

        self.u0_layer = tf.keras.layers.Conv2D(1, (1,1), activation='linear', padding='same', name='u1')

        self.concat1 = tf.keras.layers.Concatenate()
        self.concat3 = tf.keras.layers.Concatenate()

    def call(self, inputs):
        d1 = self.d1_layer(inputs)
        d2 = self.d2_layer(d1)
        d3 = self.d3_layer(d2)
        d4 = self.d4_layer(d3)

        u4 = self.u4_layer(d4)
        u3 = self.u3_layer(u4)
        c3 = self.concat3([u3, d3])
        u2 = self.u2_layer(c3)
        u1 = self.u1_layer(u2)
        c1 = self.concat1([u1, d1])

        return self.u0_layer(c1)

# Cell
def get_compiled_UnetModel(kernel_sizes, filter_sizes, input_shape):
    model = UnetModel(kernel_sizes, filter_sizes)
    model.build(input_shape)

    optimizer = tf.keras.optimizers.Adam()
    model.compile(loss='mse', optimizer=optimizer, metrics=['mae'])
    return model

# Cell
def plot_example(target, pred):
    vmax = min(np.max(pred), np.max(target))
    vmin = 0

    fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(10,5))
    ax0.imshow(np.squeeze(pred), vmin=vmin, vmax=vmax, cmap='seismic')
    ax0.set_title('prediction')

    im = ax1.imshow(np.squeeze(target), vmin=vmin, vmax=vmax, cmap='seismic')
    ax1.set_title('target')

    fig.subplots_adjust(right=0.8)
    cbar_ax = fig.add_axes([0.85, 0.2, 0.02, 0.6])
    fig.colorbar(im, cax=cbar_ax)