# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/notebooks/02_input_fields.ipynb (unless otherwise specified).

__all__ = ['MaterialFieldMaker', 'GeometricFieldMaker']

# Cell
import os
import pickle

import numpy as np
from scipy.spatial.distance import cdist

import accelerate_simulations
from ..geometry import GeometryRasterizer

# Cell
class MaterialFieldMaker:
    def __init__(self, geometry_rasterizer: GeometryRasterizer, material_properties):
        self.elements = geometry_rasterizer.elements
        self.x, self.y, self.labels_fields = geometry_rasterizer.get_label_fields()
        self.material_properties = material_properties

    def __call__(self):
        material_fields = []
        for properties in self.material_properties.values():
            material_field = np.zeros_like(self.labels_fields)
            for name, value in properties.items():
                label = self.elements[name][0]
                cond = (self.labels_fields == label)
                material_field[cond] = value

            material_fields.append(material_field)
        return np.stack(material_fields, axis=-1)

# Cell
class GeometricFieldMaker:
    def __init__(self, geometry_rasterizer: GeometryRasterizer, names_boundary, scaling_factor):
        geometry_rasterizer.rasterize()
        self.elements = geometry_rasterizer.elements
        self.x, self.y, self.labels_fields = geometry_rasterizer.get_label_fields()
        self.names_boundary = names_boundary
        self.scaling_factor = scaling_factor

    def __call__(self):
        geometric_fields = []
        for name in self.names_boundary:
            label = self.elements[name][0]
            grid_flat, grid_flat_some = self._get_grid(self.x, self.y, label)
            geometric_field = self._make_geometric_field(grid_flat, grid_flat_some)
            geometric_field = geometric_field.reshape(len(self.x), len(self.y))
            geometric_fields.append(geometric_field)

        return np.stack(geometric_fields, axis=-1)

    def _get_grid(self, x, y, label_field):
        grid_x, grid_y = np.meshgrid(x, y)

        cond = (self.labels_fields==label_field)
        grid_x_some = grid_x[cond]
        grid_y_some = grid_y[cond]

        grid_flat = np.hstack([grid_x.flatten()[:, None], grid_y.flatten()[:, None]])
        grid_flat_some = np.hstack([grid_x_some.flatten()[:, None], grid_y_some.flatten()[:, None]])

        return grid_flat, grid_flat_some

    def _dist_radial(self, x):
        return np.exp(-self.scaling_factor * x/(x.max()+1e-8))

    def _make_geometric_field(self, grid_flat, grid_flat_some):
        dist_point_to_boundary = cdist(grid_flat, grid_flat_some)
        dist_point_to_boundary = np.min(dist_point_to_boundary, axis=1)
        return self._dist_radial(dist_point_to_boundary)