# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_random_circle_in_box": "00_abstract_geometry.ipynb",
         "has_enough_distance_from_circles": "00_abstract_geometry.ipynb",
         "get_random_circle_radius": "00_abstract_geometry.ipynb",
         "AbstractGeometry": "00_abstract_geometry.ipynb",
         "get_circle_info": "01_meshed_geometry.ipynb",
         "make_msh": "01_meshed_geometry.ipynb",
         "element_to_tag": "01_rasterized_geometry.ipynb",
         "GeometryRasterizer": "01_rasterized_geometry.ipynb",
         "MaterialFieldMaker": "02_input_fields.ipynb",
         "GeometricFieldMaker": "02_input_fields.ipynb",
         "VTUContent": "02_interpolate_target.ipynb",
         "read_vtu_file": "02_interpolate_target.ipynb",
         "make_grid": "02_interpolate_target.ipynb",
         "compute_tri3_shape_function_at": "02_interpolate_target.ipynb",
         "find_grids_in_each_element": "02_interpolate_target.ipynb",
         "interpolate": "02_interpolate_target.ipynb",
         "load_data": "03_train.ipynb",
         "make_dataset": "03_train.ipynb",
         "GoogleNetLayer": "03_train.ipynb",
         "GoogleNetTransposedLayer": "03_train.ipynb",
         "UnetModel": "03_train.ipynb",
         "get_compiled_UnetModel": "03_train.ipynb",
         "plot_example": "03_train.ipynb"}

modules = ["geometry/abstract_geometry.py",
           "geometry/meshed_geometry.py",
           "geometry/rasterized_geometry.py",
           "preprocess/input_fields.py",
           "preprocess/interpolate_target.py",
           "train/model.py"]

doc_url = "https://fghavamian.github.io/accelerate_simulations/"

git_url = "https://github.com/fghavamian/accelerate_simulations/tree/master/"

def custom_doc_links(name): return None
