# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_rasterized_geometry.ipynb (unless otherwise specified).

__all__ = []

# Cell
from shapely.geometry import Point, box, Polygon, MultiPoint, MultiPolygon, LineString, MultiLineString
from geocube.api.core import make_geocube
import geopandas as gpd
import numpy as np


from geometry.abstract_geometry import AbstractGeometry